In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dummytest.csv")

In [3]:
df.head()

,lead_id,product,product_category,income_group,year,_10th,_12th,_ug3yrs,_ug4yrs,_pg,_pgexec,_certification,_parentalPrimaryEdu,_parentalSecondaryEdu,_healthCare,_fmcg,_automobiles,_insaurance,_realEstate,_banking
0,cfcd208495d565ef66e7dff9f98764da,Project_A,3BHK,Low,2018,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,c4ca4238a0b923820dcc509a6f75849b,Type_B,Dengue,Medium,2016,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,c81e728d9d4c2f636f067f89cc14862c,UG,BCA,High,2018,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,eccbc87e4b5ce2fe28308fd9f2a7baf3,UG,B.Tech,Medium,2013,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,a87ff679a2f3e71d9181a67b7542122c,PG,M.Tech,Low,2013,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [4]:
df.columns

Index(['lead_id', 'product', 'product_category', 'income_group', 'year',
       '_10th', '_12th', '_ug3yrs', '_ug4yrs', '_pg', '_pgexec',
       '_certification', '_parentalPrimaryEdu', '_parentalSecondaryEdu',
       '_healthCare', '_fmcg', '_automobiles', '_insaurance', '_realEstate',
       '_banking'],
      dtype='object')

In [6]:
df_output = df[['_10th', '_12th', '_ug3yrs', '_ug4yrs', '_pg', '_pgexec',
       '_certification', '_parentalPrimaryEdu', '_parentalSecondaryEdu',
       '_healthCare', '_fmcg', '_automobiles', '_insaurance', '_realEstate',
       '_banking']]

In [12]:
df_output.head()

,_10th,_12th,_ug3yrs,_ug4yrs,_pg,_pgexec,_certification,_parentalPrimaryEdu,_parentalSecondaryEdu,_healthCare,_fmcg,_automobiles,_insaurance,_realEstate,_banking
0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [8]:
import numpy as np

In [65]:
x = np.array(df_output)

In [66]:
from scipy.sparse import csc_matrix

In [67]:
csc = csc_matrix(x)

In [68]:
coo = csc.tocoo(copy=False)

In [69]:
 y = pd.DataFrame({'index': coo.row, 'col': coo.col, 'data': coo.data}
                 )[['index', 'col', 'data']].sort_values(['index', 'col']
                 ).reset_index(drop=True)

In [70]:
y.columns

Index(['index', 'col', 'data'], dtype='object')

In [71]:
df["Output"] = y ["col"]

In [72]:
df.columns

Index(['lead_id', 'product', 'product_category', 'income_group', 'year',
       '_10th', '_12th', '_ug3yrs', '_ug4yrs', '_pg', '_pgexec',
       '_certification', '_parentalPrimaryEdu', '_parentalSecondaryEdu',
       '_healthCare', '_fmcg', '_automobiles', '_insaurance', '_realEstate',
       '_banking', 'Output'],
      dtype='object')

In [73]:
df_final = df.drop(['lead_id','_10th', '_12th', '_ug3yrs', '_ug4yrs', '_pg', '_pgexec',
       '_certification', '_parentalPrimaryEdu', '_parentalSecondaryEdu',
       '_healthCare', '_fmcg', '_automobiles', '_insaurance', '_realEstate',
       '_banking'],axis = 1)

In [74]:
df_final.head()

     product product_category income_group  year  Output
0  Project_A             3BHK          Low  2018      13
1     Type_B           Dengue       Medium  2016       9
2         UG              BCA         High  2018       2
3         UG           B.Tech       Medium  2013       3
4         PG           M.Tech          Low  2013       4

In [75]:
df_output.columns

Index(['_10th', '_12th', '_ug3yrs', '_ug4yrs', '_pg', '_pgexec',
       '_certification', '_parentalPrimaryEdu', '_parentalSecondaryEdu',
       '_healthCare', '_fmcg', '_automobiles', '_insaurance', '_realEstate',
       '_banking'],
      dtype='object')

In [76]:
df_final.Output.unique()

array([13,  9,  2,  3,  4], dtype=int64)

In [77]:
z = list(df_final.Output)

In [78]:
A = []
for i in z:
    if i==13:
        A.append('_realEstate')
    if i== 9:
        A.append('_healthCare')
    if i == 2:
         A.append('_ug3yrs')
    if i == 3:
         A.append('_ug4yrs')
    if i == 4:
         A.append('_pg')

In [79]:
A

['_realEstate',
 '_healthCare',
 '_ug3yrs',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug4yrs',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_ug4yrs',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_ug3yrs',
 '_ug4yrs',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_ug4yrs',
 '_realEstate',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_ug4yrs',
 '_ug4yrs',
 '_ug4yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_realEstate',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_ug4yrs',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug4yrs',
 '_ug3yrs',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_ug3yrs',
 '_ug4yrs',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_ug4yrs',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_healthCare',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_realEstate',
 '_ug3yrs',
 '_realEstate',
 '_ug4yrs',
 '_ug4yrs',
 '_ug3yrs',
 '_ug4yrs',
 '_realEstate',
 '_realEstate',
 '_ug3yrs',
 '_ug3yrs',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_ug4yrs',
 '_ug4yrs',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_ug4yrs',
 '_realEstate',
 '_ug3yrs',
 '_healthCare',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_ug4yrs',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_ug4yrs',
 '_pg',
 '_healthCare',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_ug4yrs',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_healthCare',
 '_ug4yrs',
 '_ug3yrs',
 '_ug3yrs',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_ug4yrs',
 '_pg',
 '_ug4yrs',
 '_ug3yrs',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_ug4yrs',
 '_realEstate',
 '_pg',
 '_ug4yrs',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug4yrs',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_ug3yrs',
 '_ug4yrs',
 '_ug3yrs',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_healthCare',
 '_ug4yrs',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_ug3yrs',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_ug4yrs',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_ug4yrs',
 '_pg',
 '_healthCare',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_ug4yrs',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_ug3yrs',
 '_realEstate',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_ug3yrs',
 '_healthCare',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_ug3yrs',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_pg',
 '_pg',
 '_realEstate',
 '_pg',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_ug3yrs',
 '_realEstate',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_ug4yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_healthCare',
 '_realEstate',
 '_ug3yrs',
 '_pg',
 '_realEstate',
 '_ug3yrs',
 '_ug3yrs',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_ug4yrs',
 '_healthCare',
 '_healthCare',
 '_healthCare',
 '_pg',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_healthCare',
 '_ug3yrs',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_pg',
 '_pg',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_pg',
 '_ug4yrs',
 '_realEstate',
 '_pg',
 '_pg',
 '_healthCare',
 '_realEstate',
 '_realEstate',
 '_pg',
 '_healthCare',
 '_pg',
 '_pg',
 ...]

In [80]:
df_final["Output2"] = A

In [81]:
df_final

          product  product_category income_group  year  Output      Output2
0       Project_A              3BHK          Low  2018      13  _realEstate
1          Type_B            Dengue       Medium  2016       9  _healthCare
2              UG               BCA         High  2018       2      _ug3yrs
3              UG            B.Tech       Medium  2013       3      _ug4yrs
4              PG            M.Tech          Low  2013       4          _pg
5              PG               MBA         High  2019       4          _pg
6              PG            M.Tech       Medium  2012       4          _pg
7              PG               MBA       Medium  2017       4          _pg
8          Type_B            Cardio          Low  2015       9  _healthCare
9          Type_A          diabetes       Medium  2012       9  _healthCare
10      Project_C              4BHK         High  2015      13  _realEstate
11      Project_A              4BHK          Low  2018      13  _realEstate
12             PG               MBA       Medium  2017       4          _pg
13         Type_A    Blood Pressure       Medium  2017       9  _healthCare
14      Project_B              1BHK         High  2016      13  _realEstate
15         Type_B            Cardio          Low  2015       9  _healthCare
16         Type_B            Cardio       Medium  2012       9  _healthCare
17             PG               MBA         High  2012       4          _pg
18             PG               MBA       Medium  2012       4          _pg
19          UG-PG              PGDM       Medium  2012       4          _pg
20             UG               BBA          Low  2014       2      _ug3yrs
21      Project_C              3BHK          Low  2017      13  _realEstate
22             UG              B.Sc         High  2015       2      _ug3yrs
23             PG               MBA       Medium  2012       4          _pg
24             PG            M.Tech         High  2012       4          _pg
25         Type_B            Cardio          Low  2013       9  _healthCare
26         Type_B            Dengue       Medium  2016       9  _healthCare
27         Type_B            Cardio       Medium  2012       9  _healthCare
28         Type_B         Neurology          Low  2015       9  _healthCare
29         Type_B            Dengue          Low  2019       9  _healthCare
...           ...               ...          ...   ...     ...          ...
299970     Type_A          diabetes       Medium  2012       9  _healthCare
299971      UG-PG          M.Pharma       Medium  2014       4          _pg
299972  Project_C              4BHK          Low  2013      13  _realEstate
299973  Project_A              2BHK          Low  2013      13  _realEstate
299974     Type_A          diabetes          Low  2015       9  _healthCare
299975      UG-PG          M.Pharma          Low  2013       4          _pg
299976         PG              M.Sc         High  2012       4          _pg
299977  Project_A              2BHK          Low  2018      13  _realEstate
299978         UG            B.Tech       Medium  2013       3      _ug4yrs
299979         UG            B.Tech       Medium  2016       3      _ug4yrs
299980         PG               MBA       Medium  2012       4          _pg
299981         PG            M.Tech       Medium  2015       4          _pg
299982     Type_A          diabetes       Medium  2012       9  _healthCare
299983      UG-PG          M.Pharma         High  2017       4          _pg
299984         PG               MBA       Medium  2017       4          _pg
299985     Type_B         Neurology       Medium  2016       9  _healthCare
299986         PG            M.Tech       Medium  2012       4          _pg
299987      UG-PG  Hotel Management       Medium  2015       4          _pg
299988         PG               MBA         High  2019       4          _pg
299989      UG-PG          M.Pharma         High  2017       4          _pg
299990  Project_C              4BHK       Medium  2016      13  _realEstate
299991  Project_A              2BHK         High  2018      13  _realEstate
299992     Type_B             Ortho       Medium  2012       9  _healthCare
299993  Project_A              3BHK       Medium  2019      13  _realEstate
299994         PG              M.Sc       Medium  2014       4          _pg
299995         PG               MBA       Medium  2012       4          _pg
299996      UG-PG          B.E-5yrs         High  2016       4          _pg
299997      UG-PG              PGDM         High  2013       4          _pg
299998      UG-PG              PGDM       Medium  2012       4          _pg
299999         UG               BCA       Medium  2012       2      _ug3yrs

[300000 rows x 6 columns]

In [87]:
df_final.columns

Index(['product', 'product_category', 'income_group', 'year', 'Output',
       'Output2'],
      dtype='object')

In [88]:
df_final.dtypes

product             object
product_category    object
income_group        object
year                 int64
Output               int32
Output2             object
dtype: object

In [91]:
X = df_final[['product', 'product_category', 'income_group']]
y = df_final['Output']

In [92]:
X = X.astype("category")

In [94]:
X['product_cat'] = X['product'].cat.codes
X['product_category_cat'] = X['product_category'].cat.codes
X['income_cat'] = X['income_group'].cat.codes

In [113]:
X["product"].unique()

[Project_A, Type_B, UG, PG, Type_A, Project_C, Project_B, UG-PG]
Categories (8, object): [Project_A, Type_B, UG, PG, Type_A, Project_C, Project_B, UG-PG]

In [114]:
X.head()

,product,product_category,income_group,product_cat,product_category_cat,income_cat
0,Project_A,3BHK,Low,1,3,1
1,Type_B,Dengue,Medium,5,15,2
2,UG,BCA,High,6,12,0
3,UG,B.Tech,Medium,6,10,2
4,PG,M.Tech,Low,0,19,1

In [96]:
X.columns

Index(['product', 'product_category', 'income_group', 'product_cat',
       'product_category_cat', 'income_cat'],
      dtype='object')

In [98]:
X_final = X[['product_cat','product_category_cat', 'income_cat']]

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
X_final.columns

Index(['product_cat', 'product_category_cat', 'income_cat'], dtype='object')

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.33, random_state=42)

In [120]:

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, bootstrap = True, max_features = 'sqrt')

# Fit on training data

model.fit(X_train,  y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [104]:
rf_predictions = model.predict(X_test)

# Probabilities for each class

#rf_probs = model.predict_proba(test)[:, 1]

In [105]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, rf_predictions)

1.0

In [123]:
rf_predictions [0:15]

array([13, 13,  9,  9,  9, 13,  4, 13,  2,  9,  4, 13, 13, 13, 13],
      dtype=int32)

In [117]:
model.predict([2,5],[5,3])

TypeError: predict() takes 2 positional arguments but 3 were given

In [134]:
X_test.head()

        product_cat  product_category_cat  income_cat
4941              3                     4           1
51775             2                     2           1
115253            4                    13           2
299321            5                    21           2
173570            4                    27           1